version: '3.8'

services:
  next-dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env.local
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
