name: Docker Image CI

on:
  push:
    branches: ['master']

jobs:
  build:
    runs-on: [self-hosted, arm64]

    steps:
      # Checkout the code from the repository
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USER }}" --password-stdin

      - name: Build and tag the Docker image
        run: |
          docker buildx build . \
            --file Dockerfile \
            --tag avukalov/next-dashboard:latest \
            --build-arg NEXT_PUBLIC_HASURA_WS_ARG=${{ secrets.NEXT_PUBLIC_HASURA_WS }} \
            --build-arg HASURA_URL_ARG=${{ secrets.HASURA_URL }} \
            --build-arg HASURA_SECRET_ARG=${{ secrets.HASURA_SECRET }} \

      - name: Push the Docker image
        run: |
          docker push avukalov/next-dashboard:latest
