name: Docker Image CI

on:
  push:
    branches: ['develop']
  pull_request:
    branches: ['develop']

jobs:
  # config:
  #   runs-on: ubuntu-latest

  # steps:
  #   - name: Echo secrets
  #     run: |
  #       echo 'NEXT_PUBLIC_HASURA_WS=${{ secrets.NEXT_PUBLIC_HASURA_WS }}' >> .env.local
  #       echo 'HASURA_SECRET=${{ secrets.HASURA_SECRET }}' >> .env.local
  #       echo 'HASURA_URL=${{ secrets.HASURA_URL }}' >> .env.local
  #       echo 'AUTH0_AUDIENCE=${{ secrets.AUTH0_AUDIENCE }}' >> .env.local
  #       echo 'AUTH0_BASE_URL=${{ secrets.AUTH0_BASE_URL }}' >> .env.local
  #       echo 'AUTH0_SECRET=${{ secrets.AUTH0_SECRET }}' >> .env.local
  #       echo 'AUTH0_ISSUER_BASE_URL=${{ secrets.AUTH0_ISSUER_BASE_URL }}' >> .env.local
  #       echo 'AUTH0_CLIENT_ID=${{ secrets.AUTH0_CLIENT_ID }}' >> .env.local
  #       echo 'AUTH0_CLIENT_SECRET=${{ secrets.AUTH0_CLIENT_SECRET }}' >> .env.local
  #       echo 'POSTGRES_URL=${{ secrets.POSTGRES_URL }}' >> .env.local

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: |
          echo 'NEXT_PUBLIC_HASURA_WS=${{ secrets.NEXT_PUBLIC_HASURA_WS }}' >> .env.local
          echo 'HASURA_SECRET=${{ secrets.HASURA_SECRET }}' >> .env.local
          echo 'HASURA_URL=${{ secrets.HASURA_URL }}' >> .env.local
          echo 'AUTH0_AUDIENCE=${{ secrets.AUTH0_AUDIENCE }}' >> .env.local
          echo 'AUTH0_BASE_URL=${{ secrets.AUTH0_BASE_URL }}' >> .env.local
          echo 'AUTH0_SECRET=${{ secrets.AUTH0_SECRET }}' >> .env.local
          echo 'AUTH0_ISSUER_BASE_URL=${{ secrets.AUTH0_ISSUER_BASE_URL }}' >> .env.local
          echo 'AUTH0_CLIENT_ID=${{ secrets.AUTH0_CLIENT_ID }}' >> .env.local
          echo 'AUTH0_CLIENT_SECRET=${{ secrets.AUTH0_CLIENT_SECRET }}' >> .env.local
          echo 'POSTGRES_URL=${{ secrets.POSTGRES_URL }}' >> .env.local
          docker build . --file Dockerfile --tag my-image-name:$(date +%s)
